"""
Breakout V5.1 — Adaptive Conviction Engine (Revised Architecture)
=================================================================

3 Hard Gates + 4 Score Boosters + LLM Code Patches + LLM Intelligence Layer.

ARCHITECTURE:
  3 Hard Gates (must pass):
    G1. Momentum — RS >= 70th percentile, price > 50 DMA
    G3. Institutional Footprint — at least 1 signal (OBV, vol pattern)
    G5. Technical Setup — resistance detected, 2+ touches, flat ceiling

  4 Score Boosters (add conviction, NOT gates):
    B0. Market Regime — +15 if Nifty above EMAs
    B2. Sector Strength — +10 if top sector
    B4. Volatility Squeeze — +15 if in squeeze
    B6. Weekly Confirmation — +15 if weekly aligned

  LLM Code Patches:
    Auto-loads patch_filter() functions from Output/breakout_patches/.
    Generated by breakout_daily_tracker.py after failure analysis.

  LLM Intelligence Layer (optional, requires Azure OpenAI):
    - Market Regime Assessment: dynamically adjusts thresholds or skips
      scanning in hostile markets.
    - Conviction Court: final qualitative review of each pick for base
      quality, risk profile, timing, and kill signals.
    - R:R enforcement: minimum 1.0 risk/reward ratio.
    Disable with --no-llm; scanner works identically without LLM.

  Minimum conviction score >= 45/100 to recommend.

Usage:
  python3 breakout_v5.py                    # live scan
  python3 breakout_v5.py --backtest         # historical backtest
  python3 breakout_v5.py -v                 # verbose output
  python3 breakout_v5.py --no-llm           # skip LLM intelligence layer
"""

import os, sys, gzip, json, datetime, argparse, warnings, traceback
from typing import Optional, Dict, List, Tuple
from collections import defaultdict, Counter
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

try:
    from llm_client import llm_json, is_available as llm_is_available
except ImportError:
    llm_json = None
    def llm_is_available(): return False

_USE_LLM = True

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CACHE_DIR = os.path.join(SCRIPT_DIR, ".ohlcv_cache")
TODAY = datetime.date.today()

# ═══════════════════════════════════════════════════════════════════════════════
# TUNABLE PARAMETERS
# ═══════════════════════════════════════════════════════════════════════════════

class Params:
    """All tunable parameters. Optimized via backtest."""

    # Hard Gate 1: Momentum (relaxed from v5.0)
    RS_MIN_PERCENTILE = 70      # Top 30% (was 85)
    RS_LOOKBACK_SHORT = 63
    RS_LOOKBACK_LONG = 126
    RS_SHORT_WEIGHT = 0.4
    RS_LONG_WEIGHT = 0.6
    REQUIRE_ABOVE_MA50 = True   # Price > 50 DMA (kept)
    REQUIRE_ABOVE_MA200 = False # Relaxed — some turnarounds break out below 200
    REQUIRE_MA200_SLOPE = False # Relaxed
    REQUIRE_GOLDEN_CROSS = False # Relaxed

    # Hard Gate 3: Institutional Footprint
    OBV_SHORT_WINDOW = 10
    OBV_LONG_WINDOW = 50

    # Hard Gate 5: Technical Setup
    RES_BAND_PCT = 0.025
    MIN_TOUCHES = 2             # Lowered from 3
    PROXIMITY_MIN = -0.04       # Widened from -0.02
    PROXIMITY_MAX = 0.03        # Widened from 0.015
    BASE_MIN_DAYS = 15          # Shorter bases ok for SME
    BASE_MAX_DAYS = 180
    BASE_MAX_RANGE = 0.40       # Widened from 0.35
    FRACTAL_K_TIGHT = 3
    FRACTAL_K_BROAD = 8
    FAILED_BO_LOOKBACK = 15
    HIGHER_LOWS_MIN_SWINGS = 3

    # Booster B0: Market Regime
    MARKET_EMA_PERIOD = 20
    MARKET_SMA_PERIOD = 50
    MARKET_ADX_PERIOD = 14

    # Booster B4: Volatility Squeeze
    BB_PERIOD = 20
    BB_STD = 2.0
    KC_PERIOD = 20
    KC_ATR_MULT = 1.5
    SQUEEZE_MIN_BARS = 2
    ATR_COMPRESSION_RATIO = 0.65

    # Booster B6: Weekly Confirmation
    WEEKLY_MA_PERIOD = 10
    WEEKLY_NEAR_HIGH_PCT = 0.08
    WEEKLY_RSI_MIN = 45
    WEEKLY_RSI_MAX = 80
    WEEKLY_RSI_PERIOD = 14

    # Score weights (total 100)
    W_RS = 15           # RS percentile quality
    W_PROXIMITY = 15    # How close to breakout
    W_BASE = 10         # Base quality (touches, higher lows, VCP)
    W_INST = 10         # Number of institutional signals
    W_MARKET = 15       # Booster: market regime
    W_SECTOR = 10       # Booster: sector strength
    W_SQUEEZE = 15      # Booster: volatility squeeze
    W_WEEKLY = 10       # Booster: weekly confirmation

    # Minimum score to recommend
    MIN_SCORE = 45

    # Max recommendations per scan (top N by score)
    MAX_PICKS = 10

    # Universe filters
    MIN_AVG_VOLUME = 5000       # Drastically lowered from 50K — SME stocks trade thin
    MIN_AVG_TURNOVER = 500000   # ₹5L daily turnover minimum (NEW — replaces volume)
    MIN_PRICE = 5.0             # Lowered from 10
    MIN_HISTORY_DAYS = 60       # Lowered from 100 — allow newer IPOs

    # Backtest
    OUTCOME_DAYS = 5
    BREAKOUT_THRESHOLD = 0.005


P = Params()

PATCH_DIR = os.path.join(SCRIPT_DIR, "Output", "breakout_patches")
_loaded_patches = []


def _load_patches():
    """Auto-load LLM-generated patch_filter functions from Output/breakout_patches/.
    Each patch file must define a patch_filter(pick, df) -> bool function.
    """
    global _loaded_patches
    if _loaded_patches or not os.path.isdir(PATCH_DIR):
        return
    import importlib.util
    for fname in sorted(os.listdir(PATCH_DIR)):
        if not fname.startswith("patch_") or not fname.endswith(".py"):
            continue
        fpath = os.path.join(PATCH_DIR, fname)
        try:
            spec = importlib.util.spec_from_file_location(
                fname.replace(".py", ""), fpath)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            if hasattr(mod, "patch_filter") and callable(mod.patch_filter):
                _loaded_patches.append(mod.patch_filter)
        except Exception:
            continue
    if _loaded_patches:
        print(f"  Loaded {len(_loaded_patches)} LLM code patches")


# ═══════════════════════════════════════════════════════════════════════════════
# DATA LOADING
# ═══════════════════════════════════════════════════════════════════════════════

def load_all_cached_ohlcv() -> Dict[str, pd.DataFrame]:
    """Load ALL cached OHLCV data from disk. Returns {ticker: DataFrame}."""
    data = {}
    if not os.path.isdir(CACHE_DIR):
        print(f"  ERROR: Cache directory {CACHE_DIR} not found")
        return data
    files = [f for f in os.listdir(CACHE_DIR) if f.endswith('__1d.csv.gz')]
    print(f"  Loading {len(files)} cached OHLCV files...")
    for fname in files:
        try:
            parts = fname.replace('__1d.csv.gz', '').rsplit('_', 1)
            if len(parts) != 2: continue
            ticker = parts[0]
            if not (ticker.endswith('.NS') or ticker.endswith('.BO')): continue
            filepath = os.path.join(CACHE_DIR, fname)
            with gzip.open(filepath, 'rt') as f:
                header = f.readline()
                if not header.startswith('# ohlcv_cache'):
                    f.seek(0)
                df = pd.read_csv(f, parse_dates=['Date'], index_col='Date')
            if df.empty or len(df) < 30: continue
            required = ['Open', 'High', 'Low', 'Close', 'Volume']
            if not all(c in df.columns for c in required): continue
            df = df[required].dropna()
            df = df[df['Volume'] > 0]
            df = df[df['High'] >= df['Low']]
            df = df.sort_index()
            df = df[~df.index.duplicated(keep='last')]
            if len(df) >= 30:
                data[ticker] = df
        except Exception:
            continue
    print(f"  Loaded {len(data)} tickers with valid data")
    return data


def slice_data(ohlcv, as_of_date):
    """Slice all OHLCV data up to a given date for backtesting."""
    ts = pd.Timestamp(as_of_date)
    return {tk: df[df.index <= ts] for tk, df in ohlcv.items()
            if len(df[df.index <= ts]) >= P.MIN_HISTORY_DAYS}


def get_outcome(df, scan_date, R):
    """Check if price broke above R within OUTCOME_DAYS after scan_date."""
    ts = pd.Timestamp(scan_date)
    future = df[df.index > ts].head(P.OUTCOME_DAYS)
    if future.empty:
        return {"success": False, "max_gain_pct": 0, "days_to_breakout": 0,
                "max_drawdown_pct": 0}
    scan_close = float(df[df.index <= ts].iloc[-1]["Close"])
    target = R * (1 + P.BREAKOUT_THRESHOLD)
    max_high = float(future["High"].max())
    min_low = float(future["Low"].min())
    max_gain = (max_high - scan_close) / scan_close * 100
    max_dd = (scan_close - min_low) / scan_close * 100
    days_to_bo = 0
    for i, (_, row) in enumerate(future.iterrows(), 1):
        if float(row["High"]) >= target:
            days_to_bo = i; break
    return {"success": bool(max_high >= target), "max_gain_pct": round(max_gain, 2),
            "days_to_breakout": days_to_bo, "max_drawdown_pct": round(max_dd, 2)}


# ═══════════════════════════════════════════════════════════════════════════════
# TECHNICAL INDICATORS
# ═══════════════════════════════════════════════════════════════════════════════

def ema(s, p):
    """Exponential moving average."""
    return s.ewm(span=p, adjust=False).mean()


def sma(s, p):
    """Simple moving average."""
    return s.rolling(p).mean()


def atr(df, n=14):
    """Average true range over n periods."""
    h, l, c = df["High"], df["Low"], df["Close"]
    pc = c.shift(1)
    tr = pd.concat([(h-l), (h-pc).abs(), (l-pc).abs()], axis=1).max(axis=1)
    return tr.rolling(n).mean()

def rsi(s, p=14):
    """Relative Strength Index."""
    d = s.diff()
    g = d.where(d>0, 0.0)
    lo = (-d).where(d<0, 0.0)
    ag = g.ewm(alpha=1/p, min_periods=p, adjust=False).mean()
    al = lo.ewm(alpha=1/p, min_periods=p, adjust=False).mean()
    rs = ag / al.replace(0, np.nan)
    return 100 - (100 / (1+rs))

def adx(df, p=14):
    """Average Directional Index."""
    h, l, c = df["High"], df["Low"], df["Close"]
    pdm = h.diff().clip(lower=0)
    mdm = (-l.diff()).clip(lower=0)
    pdm = pdm.where(pdm > mdm, 0)
    mdm = mdm.where(mdm > pdm, 0)
    tr = pd.concat([(h-l), (h-c.shift(1)).abs(), (l-c.shift(1)).abs()], axis=1).max(axis=1)
    atr_s = tr.ewm(alpha=1/p, min_periods=p, adjust=False).mean()
    pdi = 100*(pdm.ewm(alpha=1/p, min_periods=p, adjust=False).mean()/atr_s)
    mdi = 100*(mdm.ewm(alpha=1/p, min_periods=p, adjust=False).mean()/atr_s)
    dx = 100*((pdi-mdi).abs()/(pdi+mdi).replace(0, np.nan))
    return dx.ewm(alpha=1/p, min_periods=p, adjust=False).mean()

def obv(df):
    """On-Balance Volume."""
    sign = np.sign(df["Close"].diff().fillna(0))
    return (sign * df["Volume"]).cumsum()

def bollinger_bands(df, p=20, std=2.0):
    """Bollinger Bands: upper, middle, lower."""
    mid = sma(df["Close"], p)
    s = df["Close"].rolling(p).std()
    return mid + std*s, mid, mid - std*s

def keltner_channels(df, p=20, mult=1.5):
    """Keltner Channels: upper, middle, lower."""
    mid = ema(df["Close"], p)
    a = atr(df, p)
    return mid + mult*a, mid, mid - mult*a

def linreg_slope(y):
    """Linear regression slope of a series."""
    v = y.dropna().values
    if len(v) < 5: return 0.0
    return float(np.polyfit(np.arange(len(v)), v, 1)[0])

def fractal_pivots(highs, k=3):
    """Identify fractal pivot highs (local maxima with k bars on each side)."""
    mask = pd.Series(False, index=highs.index)
    v = highs.values; n = len(v)
    for i in range(k, n-k):
        w = v[max(0, i-k):i+k+1]
        if v[i] == w.max() and np.sum(w == v[i]) == 1:
            mask.iloc[i] = True
    return mask

def resample_weekly(df):
    """Resample daily OHLCV to weekly (Friday close)."""
    return df.resample('W-FRI').agg({
        'Open':'first', 'High':'max', 'Low':'min', 'Close':'last', 'Volume':'sum'
    }).dropna()


# ═══════════════════════════════════════════════════════════════════════════════
# HARD GATE 1: MOMENTUM (Relaxed)
# ═══════════════════════════════════════════════════════════════════════════════

def compute_rs_ratings(ohlcv, bench_close):
    """Compute relative strength percentile rankings vs benchmark."""
    raw = {}
    for tk, df in ohlcv.items():
        c = df["Close"]
        if len(c) < P.RS_LOOKBACK_SHORT: continue
        common = c.index.intersection(bench_close.index)
        if len(common) < P.RS_LOOKBACK_SHORT: continue
        stock = c.reindex(common); b = bench_close.reindex(common)

        if len(stock) >= P.RS_LOOKBACK_LONG and len(b) >= P.RS_LOOKBACK_LONG:
            sl = float(stock.iloc[-1]/stock.iloc[-P.RS_LOOKBACK_LONG])
            bl = float(b.iloc[-1]/b.iloc[-P.RS_LOOKBACK_LONG])
            rs_long = (sl/bl - 1)*100 if bl > 0 else 0
        else:
            rs_long = 0

        if len(stock) >= P.RS_LOOKBACK_SHORT:
            ss = float(stock.iloc[-1]/stock.iloc[-P.RS_LOOKBACK_SHORT])
            bs = float(b.iloc[-1]/b.iloc[-P.RS_LOOKBACK_SHORT])
            rs_short = (ss/bs - 1)*100 if bs > 0 else 0
        else:
            rs_short = 0

        raw[tk] = P.RS_SHORT_WEIGHT*rs_short + P.RS_LONG_WEIGHT*rs_long
    if not raw: return {}
    vals = sorted(raw.values()); n = len(vals)
    return {tk: round(np.searchsorted(vals, v, side='right')/n*100, 1)
            for tk, v in raw.items()}


def gate1_momentum(df, rs_rating):
    """Hard gate: RS ≥ 70th percentile + price > 50 DMA."""
    if len(df) < P.MIN_HISTORY_DAYS:
        return {"pass": False, "reason": "history"}
    if rs_rating < P.RS_MIN_PERCENTILE:
        return {"pass": False, "reason": f"rs={rs_rating:.0f}<{P.RS_MIN_PERCENTILE}"}
    c = df["Close"]; last = float(c.iloc[-1])
    ma50 = sma(c, 50)
    if P.REQUIRE_ABOVE_MA50 and not pd.isna(ma50.iloc[-1]) and last <= float(ma50.iloc[-1]):
        return {"pass": False, "reason": "below_ma50"}
    return {"pass": True, "rs_rating": rs_rating}


# ═══════════════════════════════════════════════════════════════════════════════
# HARD GATE 3: INSTITUTIONAL FOOTPRINT
# ═══════════════════════════════════════════════════════════════════════════════

def gate3_institutional(df):
    """Any one signal = pass. Four independent signals checked."""
    signals = []
    if len(df) < 30: return {"pass": False, "signals": [], "reason": "short"}

    # Signal 1: OBV divergence
    if len(df) >= P.OBV_LONG_WINDOW:
        o = obv(df)
        obv_rh = float(o.tail(P.OBV_SHORT_WINDOW).max())
        obv_ph = float(o.iloc[-P.OBV_LONG_WINDOW:-P.OBV_SHORT_WINDOW].max())
        prh = float(df["High"].tail(P.OBV_SHORT_WINDOW).max())
        pph = float(df["High"].iloc[-P.OBV_LONG_WINDOW:-P.OBV_SHORT_WINDOW].max())
        if obv_rh > obv_ph and prh < pph * 1.01:
            signals.append("obv_divergence")

    # Signal 2: Volume accumulation (OBV rising, total vol declining)
    if len(df) >= 30:
        o = obv(df)
        if linreg_slope(o.tail(20)) > 0 and linreg_slope(df["Volume"].tail(20)) < 0:
            signals.append("vol_accumulation")

    # Signal 3: Up-day volume dominance
    if len(df) >= 20:
        r = df.tail(20)
        up = r[r["Close"] > r["Close"].shift(1)]
        dn = r[r["Close"] < r["Close"].shift(1)]
        if len(up) > 0 and len(dn) > 0:
            if float(up["Volume"].mean()) > float(dn["Volume"].mean()) * 1.15:
                signals.append("up_vol_dominant")

    # Signal 4: Recent volume surge on up-close days
    if len(df) >= 10:
        last5 = df.tail(5)
        up_days = last5[last5["Close"] > last5["Open"]]
        if len(up_days) >= 3:
            avg_up_vol = float(up_days["Volume"].mean())
            avg_50_vol = float(df["Volume"].tail(50).mean()) if len(df) >= 50 else float(df["Volume"].mean())
            if avg_up_vol > avg_50_vol * 1.3:
                signals.append("recent_vol_surge")

    return {"pass": len(signals) > 0, "signals": signals,
            "reason": ",".join(signals) if signals else "no_signal"}


# ═══════════════════════════════════════════════════════════════════════════════
# HARD GATE 5: TECHNICAL SETUP
# ═══════════════════════════════════════════════════════════════════════════════

def detect_resistance(df):
    """Detect horizontal resistance via fractal pivot clustering."""
    if len(df) < P.BASE_MIN_DAYS + 20: return None
    last_close = float(df["Close"].iloc[-1])
    window = df.tail(min(300, len(df)))

    piv_t = fractal_pivots(window["High"], P.FRACTAL_K_TIGHT)
    piv_b = fractal_pivots(window["High"], P.FRACTAL_K_BROAD)
    pivots = pd.concat([window["High"][piv_t], window["High"][piv_b]]).groupby(level=0).max()
    if len(pivots) < P.MIN_TOUCHES: return None

    levels = sorted(pivots.tolist(), reverse=True)
    clusters = []
    for lvl in levels:
        placed = False
        for c in clusters:
            if abs(lvl - c["level"])/c["level"] <= P.RES_BAND_PCT:
                c["sum"] += lvl; c["count"] += 1
                c["level"] = c["sum"]/c["count"]; placed = True; break
        if not placed:
            clusters.append({"level": lvl, "sum": lvl, "count": 1})

    candidates = []
    for cl in clusters:
        R = cl["level"]
        if R <= 0: continue
        dist = (R - last_close)/last_close
        if cl["count"] < P.MIN_TOUCHES: continue
        if dist < P.PROXIMITY_MIN or dist > P.PROXIMITY_MAX: continue
        touch_dates = [ts for ts in pivots.index
                       if abs(pivots.loc[ts] - R)/R <= P.RES_BAND_PCT]
        if len(touch_dates) < P.MIN_TOUCHES: continue
        base_start = min(touch_dates)
        base_len = (df.index[-1] - base_start).days
        if base_len < P.BASE_MIN_DAYS: continue
        if base_len > P.BASE_MAX_DAYS:
            recent = [t for t in touch_dates if (df.index[-1]-t).days <= P.BASE_MAX_DAYS]
            if len(recent) < P.MIN_TOUCHES: continue
            base_start = min(recent); base_len = (df.index[-1]-base_start).days
        candidates.append({"R": R, "touches": len(touch_dates), "base_start": base_start,
                           "base_len_days": base_len, "distance_pct": dist})
    if not candidates: return None
    candidates.sort(key=lambda c: (-c["touches"], abs(c["distance_pct"])))
    best = candidates[0]
    higher = [c for c in candidates if c["R"] > best["R"]*1.02
              and c["touches"] >= max(2, int(best["touches"]*0.7))]
    if higher:
        higher.sort(key=lambda c: -c["R"]); return higher[0]
    return best


def gate5_technical(df):
    """Hard gate: resistance with flat ceiling, 2+ touches, proximity check."""
    res = detect_resistance(df)
    if res is None: return {"pass": False, "reason": "no_resistance", "R": None}
    R = res["R"]; base = df.loc[res["base_start"]:]
    if base.empty: return {"pass": False, "reason": "empty_base", "R": R}

    bh = float(base["High"].max()); bl = float(base["Low"].min())
    br = (bh - bl)/R if R > 0 else 1.0
    if br > P.BASE_MAX_RANGE:
        return {"pass": False, "reason": "base_wide", "R": R}

    seg = df.tail(P.FAILED_BO_LOOKBACK)
    if not seg.empty and bool((seg["High"] > R*1.03).any()) and float(df["Close"].iloc[-1]) < R*0.98:
        return {"pass": False, "reason": "failed_bo", "R": R}

    # FLAT CEILING CHECK: the highs across the base must be at roughly the
    # same level — a genuine horizontal ceiling, not trending highs.
    bh = base["High"].values
    nb = len(bh); t = max(1, nb // 3)
    if nb >= 9:
        h1, h2, h3 = bh[:t].max(), bh[t:2*t].max(), bh[2*t:].max()
        mx = max(h1, h2, h3)
        if any(abs(x - mx)/mx > 0.035 for x in [h1, h2, h3]):
            return {"pass": False, "reason": "ceiling_not_flat", "R": R}

    lows_idx = base["Low"].rolling(11, center=True).min() == base["Low"]
    swing_lows = base["Low"][lows_idx].dropna()
    higher_lows = (linreg_slope(swing_lows) > 0) if len(swing_lows) >= P.HIGHER_LOWS_MIN_SWINGS else False

    v50 = float(df["Volume"].rolling(50).mean().iloc[-1]) if len(df) >= 50 else 1
    v10 = float(df["Volume"].tail(10).mean())
    vdu = (1.0 - v10/v50) if v50 > 0 else 0

    # VCP contractions
    n_vcp = 0
    if len(base) >= 30:
        h = base["High"].values; l = base["Low"].values; n = len(h); k = 5
        pivs = [(i, float(h[i])) for i in range(k, n-k) if h[i] == h[max(0,i-k):i+k+1].max()]
        pbs = []
        for j in range(1, len(pivs)):
            ip, pp = pivs[j-1]; ic, _ = pivs[j]
            sl = float(l[ip:ic+1].min())
            if pp > 0: pbs.append((pp-sl)/pp)
        for j in range(1, len(pbs)):
            if pbs[j] < pbs[j-1]*0.85 and pbs[j] < 0.15: n_vcp += 1

    return {"pass": True, "R": R, "distance_pct": res["distance_pct"],
            "touches": res["touches"], "base_start": res["base_start"],
            "base_days": res["base_len_days"], "base_range": round(br*100, 1),
            "higher_lows": higher_lows, "vdu": round(vdu, 3), "n_vcp": n_vcp}


# ═══════════════════════════════════════════════════════════════════════════════
# SCORE BOOSTERS (not gates — add conviction but don't block)
# ═══════════════════════════════════════════════════════════════════════════════

def booster_market_regime(bench):
    """B0: Market health. Returns 0-15 score."""
    if bench is None or len(bench) < 60: return 0, {}
    c = bench["Close"]; last = float(c.iloc[-1])
    above_ema = last > float(ema(c, P.MARKET_EMA_PERIOD).iloc[-1])
    above_sma = last > float(sma(c, P.MARKET_SMA_PERIOD).iloc[-1])
    adx_val = float(adx(bench, P.MARKET_ADX_PERIOD).iloc[-1])
    score = sum([above_ema, above_sma, adx_val > 20])
    return round(P.W_MARKET * score/3, 1), {
        "above_ema": above_ema, "above_sma": above_sma, "adx": round(adx_val, 1)}


def booster_squeeze(df):
    """B4: Volatility compression. Returns 0-15 score."""
    if len(df) < 60: return 0, []
    types = []
    bbu, _, bbl = bollinger_bands(df, P.BB_PERIOD, P.BB_STD)
    kcu, _, kcl = keltner_channels(df, P.KC_PERIOD, P.KC_ATR_MULT)
    sq = sum(1 for i in range(-5, 0)
             if (not pd.isna(bbu.iloc[i]) and not pd.isna(kcu.iloc[i])
                 and float(bbu.iloc[i]) < float(kcu.iloc[i])
                 and float(bbl.iloc[i]) > float(kcl.iloc[i])))
    if sq >= P.SQUEEZE_MIN_BARS: types.append("bb_kc")

    a = atr(df)
    if len(a) >= 50:
        now = float(a.iloc[-10:].mean())
        then = float(a.iloc[-50:-30].mean())
        if then > 0 and now/then < P.ATR_COMPRESSION_RATIO: types.append("atr_comp")

    rr = float(df["High"].tail(10).max() - df["Low"].tail(10).min())
    br = float(df["High"].tail(50).max() - df["Low"].tail(50).min())
    if br > 0 and rr/br < 0.40: types.append("narrow_range")

    score = P.W_SQUEEZE * min(len(types)/2, 1.0)
    return round(score, 1), types


def booster_weekly(df, R):
    """B6: Weekly timeframe confirmation. Returns 0-10 score."""
    w = resample_weekly(df)
    if len(w) < 12: return 0, {}
    wc = w["Close"]; last = float(wc.iloc[-1])
    wma_val = sma(wc, P.WEEKLY_MA_PERIOD)
    if pd.isna(wma_val.iloc[-1]): return 0, {}
    above_wma = last > float(wma_val.iloc[-1])

    rh = float(wc.tail(26).max())
    pct_off = (rh - last)/rh if rh > 0 else 1
    near_high = pct_off <= P.WEEKLY_NEAR_HIGH_PCT

    wrsi = rsi(wc, P.WEEKLY_RSI_PERIOD)
    wrsi_val = float(wrsi.iloc[-1]) if not pd.isna(wrsi.iloc[-1]) else 50
    rsi_ok = P.WEEKLY_RSI_MIN <= wrsi_val <= P.WEEKLY_RSI_MAX

    checks = sum([above_wma, near_high, rsi_ok])
    score = P.W_WEEKLY * checks/3
    return round(score, 1), {"above_wma": above_wma, "near_high": near_high,
                              "weekly_rsi": round(wrsi_val, 1), "rsi_ok": rsi_ok}


# ═══════════════════════════════════════════════════════════════════════════════
# COMPOSITE SCORING
# ═══════════════════════════════════════════════════════════════════════════════

def compute_score(rs_rating, g3, g5, b0_score, b4_score, b6_score):
    """Composite 0-100 conviction score."""
    # Core (from hard gates): RS + proximity + base quality + institutional
    s_rs = P.W_RS * min(rs_rating/100, 1.0)

    dist = abs(g5.get("distance_pct", 0.05))
    s_prox = P.W_PROXIMITY * max(0, 1.0 - dist/0.04)

    touches = g5.get("touches", 0)
    hl = 1.0 if g5.get("higher_lows") else 0.5
    vcp = min(g5.get("n_vcp", 0)/2, 0.5)
    s_base = P.W_BASE * min(touches/4*0.5 + hl*0.3 + vcp + 0.2, 1.0)

    n_sig = len(g3.get("signals", []))
    s_inst = P.W_INST * min(n_sig/3, 1.0)

    total = s_rs + s_prox + s_base + s_inst + b0_score + b4_score + b6_score
    return round(total, 1)


def risk_plan(df, R, base_start):
    """Compute entry, stop, target, and risk:reward for a breakout pick."""
    last = float(df["Close"].iloc[-1])
    base = df.loc[base_start:]
    bl = float(base["Low"].min()) if not base.empty else last*0.9
    sl = float(base["Low"].tail(20).min()) if len(base) >= 20 else bl
    stop = sl * 0.99
    height = R - bl
    target = R + height
    risk = last - stop
    reward = target - last
    rr = round(reward/risk, 2) if risk > 0 else 0
    return {"entry": round(last, 2), "stop": round(stop, 2), "target": round(target, 2),
            "risk_pct": round(risk/last*100, 2) if last else 0,
            "reward_pct": round(reward/last*100, 2) if last else 0, "rr": rr}


# ═══════════════════════════════════════════════════════════════════════════════
# LLM INTELLIGENCE LAYER
# ═══════════════════════════════════════════════════════════════════════════════


def llm_market_regime(bench_df, sector_stage_data=None):
    """Assess market regime and recommend dynamic threshold adjustments.

    Called once at the top of run_scan() before any stock-level processing.
    Returns a dict with regime classification and parameter overrides, or None
    if LLM is unavailable.
    """
    if not _USE_LLM or llm_json is None or not llm_is_available():
        return None
    if bench_df is None or bench_df.empty or len(bench_df) < 60:
        return None

    c = bench_df["Close"].tail(60)
    last = float(c.iloc[-1])
    returns = c.pct_change().dropna()
    m5 = float(c.tail(5).mean())
    m20 = float(c.tail(20).mean())
    m50 = float(c.mean())
    atr_vals = (bench_df["High"] - bench_df["Low"]).tail(20)
    avg_atr = float(atr_vals.mean())
    atr_pct = round(avg_atr / last * 100, 2) if last > 0 else 0

    bench_summary = {
        "last_close": round(last, 2),
        "5d_avg": round(m5, 2),
        "20d_avg": round(m20, 2),
        "50d_avg": round(m50, 2),
        "above_20dma": last > m20,
        "above_50dma": last > m50,
        "20d_return_pct": round(float(returns.tail(20).sum() * 100), 2),
        "5d_return_pct": round(float(returns.tail(5).sum() * 100), 2),
        "avg_daily_range_pct": atr_pct,
        "max_drawdown_20d_pct": round(
            float((c.tail(20).max() - c.tail(20).min()) / c.tail(20).max() * 100), 2),
    }

    sector_summary = ""
    if sector_stage_data:
        sector_summary = json.dumps(sector_stage_data, default=str)

    system_prompt = (
        "You are a quantitative market regime analyst for Indian equities. "
        "Assess whether the current market environment is receptive to "
        "breakout strategies. You MUST respond with valid JSON only."
    )

    user_prompt = (
        "Nifty 50 benchmark (last 60 days summary):\n"
        f"{json.dumps(bench_summary, indent=1)}\n\n"
    )
    if sector_summary:
        user_prompt += f"Sector stage data:\n{sector_summary}\n\n"
    user_prompt += (
        "Evaluate breakout receptiveness. Consider:\n"
        "1. Is the market trending up (above MAs) or down?\n"
        "2. Is volatility expanding (hostile to breakouts) or contracting?\n"
        "3. How many sectors are in Stage 2 (advancing) vs Stage 3/4 (topping/declining)?\n"
        "4. Is this a broad advance or narrow/rotational?\n\n"
        "Return JSON:\n"
        '{"regime": "strong_bull | bull | neutral | cautious | hostile",\n'
        ' "breakout_receptiveness": 0-100,\n'
        ' "dynamic_adjustments": {\n'
        '   "min_score_override": 45-75 (raise in weak markets),\n'
        '   "proximity_max_override": 0.01-0.03 (tighten in cautious markets),\n'
        '   "require_squeeze": true/false (require squeeze in cautious+ markets)\n'
        ' },\n'
        ' "rationale": "1-2 sentences"}'
    )

    try:
        result = llm_json(system_prompt, user_prompt, max_tokens=1000, timeout=60)
    except Exception as e:
        print(f"  [regime] LLM failed: {e}")
        return None

    if not result or "regime" not in result:
        return None

    print(f"  [regime] {result.get('regime', 'unknown').upper()} "
          f"(receptiveness: {result.get('breakout_receptiveness', '?')}/100) "
          f"— {result.get('rationale', '')}")
    return result


def llm_conviction_court(picks, ohlcv, regime):
    """Final LLM filter: reviews each pick for base quality, risk, and kill signals.

    Called after scoring and risk_plan(), before the MAX_PICKS cap.
    Returns a filtered list of picks (rejected picks are dropped).
    """
    if not _USE_LLM or llm_json is None or not llm_is_available():
        return picks
    if not picks:
        return picks

    pick_summaries = []
    for p in picks[:20]:
        tk = p["ticker"]
        df = ohlcv.get(tk)
        summary = {
            "ticker": tk,
            "score": p["score"],
            "close": p["close"],
            "resistance": p["resistance"],
            "distance_pct": p["distance_pct"],
            "rs_rating": p["rs_rating"],
            "touches": p["touches"],
            "base_days": p["base_days"],
            "base_range": round(p.get("base_range", 0) * 100, 1),
            "higher_lows": p.get("higher_lows", False),
            "n_vcp": p.get("n_vcp", 0),
            "squeeze_type": p.get("squeeze_type", ""),
            "institutional": p.get("institutional", ""),
            "weekly_rsi": p.get("weekly_rsi", 0),
            "rr": p.get("rr", 0),
            "risk_pct": p.get("risk_pct", 0),
            "reward_pct": p.get("reward_pct", 0),
            "stop": p.get("stop", 0),
            "target": p.get("target", 0),
        }

        if df is not None and len(df) >= 10:
            last10 = df.tail(10)
            vol_50d = float(df["Volume"].tail(50).mean()) if len(df) >= 50 else 1
            summary["last_10_bars"] = [
                {"O": round(float(r["Open"]), 2), "H": round(float(r["High"]), 2),
                 "L": round(float(r["Low"]), 2), "C": round(float(r["Close"]), 2),
                 "V_ratio": round(float(r["Volume"]) / vol_50d, 2) if vol_50d > 0 else 0}
                for _, r in last10.iterrows()
            ]
            if len(df) >= 50:
                summary["vol_trend"] = ("rising" if float(df["Volume"].tail(10).mean()) >
                                        float(df["Volume"].tail(50).mean()) * 1.1
                                        else "flat_or_declining")
                rs_10d = df["Close"].tail(10)
                summary["rs_10d_change"] = round(
                    float((rs_10d.iloc[-1] / rs_10d.iloc[0] - 1) * 100), 2)

        pick_summaries.append(summary)

    regime_note = ""
    if regime:
        regime_note = (f"\nMarket regime: {regime.get('regime', 'unknown')} "
                       f"(receptiveness: {regime.get('breakout_receptiveness', '?')}/100)")

    system_prompt = (
        "You are the final conviction filter for a breakout scanner targeting "
        "95%+ success rate on Indian stocks. Your job is to find reasons to "
        "REJECT — be paranoid. A false positive costs more than a missed "
        "opportunity. You MUST respond with valid JSON only."
    )

    user_prompt = (
        f"Review these {len(pick_summaries)} breakout candidates.{regime_note}\n\n"
        "For each pick, evaluate:\n"
        "1. BASE QUALITY: Clean orderly consolidation vs choppy/messy? "
        "Volume drying up? Touches at R clean or wicky?\n"
        "2. RISK PROFILE: Is R:R >= 1.0? Stop reasonable (< 8% from entry)?\n"
        "3. TIMING: Approaching R at right speed? Too fast = chasing. "
        "Too slow = no catalyst.\n"
        "4. KILL SIGNALS: Distribution signs? Expanding range at R? "
        "Declining RS in last 10 days? Very high weekly RSI (>75 = overbought)?\n"
        "5. REGIME FIT: Does this setup match market conditions?\n\n"
        "Candidates:\n"
        + json.dumps(pick_summaries, indent=1, default=str)
        + "\n\nReturn JSON:\n"
        '{"verdicts": [{"ticker": "X.NS", "verdict": "APPROVE" or "REJECT", '
        '"conviction": 0-100, "base_quality": 0-10, '
        '"risk_assessment": "acceptable | marginal | poor", '
        '"concerns": ["list"], "thesis": "1 sentence"}]}'
    )

    try:
        result = llm_json(system_prompt, user_prompt, max_tokens=4000, timeout=120)
    except Exception as e:
        print(f"  [court] LLM conviction court failed: {e}")
        return picks

    if not result or "verdicts" not in result:
        return picks

    verdict_map = {}
    for v in result["verdicts"]:
        tk = v.get("ticker", "")
        verdict_map[tk] = v

    approved = []
    rejected_count = 0
    for p in picks:
        v = verdict_map.get(p["ticker"])
        if v and v.get("verdict") == "REJECT":
            rejected_count += 1
            continue
        if v:
            p["llm_conviction"] = v.get("conviction", 50)
            p["llm_base_quality"] = v.get("base_quality", 5)
            p["llm_thesis"] = v.get("thesis", "")
            p["llm_concerns"] = v.get("concerns", [])
        approved.append(p)

    if rejected_count:
        print(f"  [court] Conviction court: {rejected_count} rejected, "
              f"{len(approved)} approved")
    return approved


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN SCANNER
# ═══════════════════════════════════════════════════════════════════════════════

def run_scan(ohlcv, bench_df, rs_ratings, verbose=False, use_llm=True):
    """Run the scan. Returns (picks, funnel_stats).

    Auto-loads LLM-generated code patches from Output/breakout_patches/
    and applies them as additional filters after scoring. When use_llm is
    True, also runs market regime assessment and conviction court.
    """
    _load_patches()

    funnel = defaultdict(int)
    funnel["total_universe"] = len(ohlcv)
    picks = []

    regime = None
    effective_min_score = P.MIN_SCORE
    effective_prox_max = P.PROXIMITY_MAX
    if use_llm and _USE_LLM:
        regime = llm_market_regime(bench_df)
        if regime:
            if (regime.get("regime") == "hostile"
                    and regime.get("breakout_receptiveness", 100) < 30):
                print("  [regime] HOSTILE market — scanning skipped")
                funnel["regime_skip"] = 1
                return [], dict(funnel)
            adj = regime.get("dynamic_adjustments", {})
            if "min_score_override" in adj:
                effective_min_score = max(P.MIN_SCORE, int(adj["min_score_override"]))
            if "proximity_max_override" in adj:
                effective_prox_max = min(P.PROXIMITY_MAX, float(adj["proximity_max_override"]))

    b0_score, b0_detail = booster_market_regime(bench_df)
    market_ok = b0_score > P.W_MARKET * 0.5
    if verbose:
        status = "✅ FAVORABLE" if market_ok else "⚠️ WEAK (score reduced)"
        print(f"  Market: {status} — boost={b0_score}/{P.W_MARKET}, {b0_detail}")

    for tk, df in ohlcv.items():
        funnel["processed"] += 1

        # Pre-filters
        if len(df) < P.MIN_HISTORY_DAYS:
            funnel["drop_history"] += 1; continue
        last_close = float(df["Close"].iloc[-1])
        if last_close < P.MIN_PRICE:
            funnel["drop_price"] += 1; continue
        avg_vol = float(df["Volume"].tail(50).mean())
        if avg_vol < P.MIN_AVG_VOLUME:
            funnel["drop_volume"] += 1; continue
        # Turnover check (volume × price)
        avg_turnover = avg_vol * last_close
        if avg_turnover < P.MIN_AVG_TURNOVER:
            funnel["drop_turnover"] += 1; continue

        # HARD GATE 1: Momentum
        rs = rs_ratings.get(tk, 0)
        g1 = gate1_momentum(df, rs)
        if not g1["pass"]:
            funnel["g1_fail"] += 1; continue
        funnel["g1_pass"] += 1

        # HARD GATE 3: Institutional
        g3 = gate3_institutional(df)
        if not g3["pass"]:
            funnel["g3_fail"] += 1; continue
        funnel["g3_pass"] += 1

        # HARD GATE 5: Technical Setup
        g5 = gate5_technical(df)
        if not g5["pass"]:
            funnel["g5_fail"] += 1; continue
        funnel["g5_pass"] += 1

        # SCORE BOOSTERS (not gates)
        b4_score, b4_types = booster_squeeze(df)
        b6_score, b6_detail = booster_weekly(df, g5["R"])

        score = compute_score(rs, g3, g5, b0_score, b4_score, b6_score)
        if score < effective_min_score:
            funnel["low_score"] += 1; continue

        rp = risk_plan(df, g5["R"], g5["base_start"])

        # R:R enforcement — reject picks with poor risk/reward
        if rp.get("rr", 0) < 1.0:
            funnel["rr_too_low"] += 1; continue

        # Apply LLM-generated patch filters (now with real R:R)
        pick_preview = {"ticker": tk, "score": score, "close": round(last_close, 2),
                        "resistance": round(g5["R"], 2),
                        "distance_pct": round(g5["distance_pct"]*100, 2),
                        "touches": g5["touches"], "base_days": g5["base_days"],
                        "squeeze_type": ",".join(b4_types),
                        "institutional": ",".join(g3.get("signals", [])),
                        "rr": rp.get("rr", 0)}
        patch_rejected = False
        for pf in _loaded_patches:
            try:
                if not pf(pick_preview, df):
                    funnel["patch_filter"] += 1
                    patch_rejected = True
                    break
            except Exception:
                pass
        if patch_rejected:
            continue

        funnel["recommended"] += 1

        picks.append({
            "ticker": tk,
            "score": score,
            "close": round(last_close, 2),
            "resistance": round(g5["R"], 2),
            "distance_pct": round(g5["distance_pct"]*100, 2),
            "rs_rating": rs,
            "touches": g5["touches"],
            "base_days": g5["base_days"],
            "base_range": g5["base_range"],
            "higher_lows": g5["higher_lows"],
            "n_vcp": g5["n_vcp"],
            "squeeze_type": ",".join(b4_types),
            "institutional": ",".join(g3.get("signals", [])),
            "weekly_rsi": b6_detail.get("weekly_rsi", 0),
            "market_boost": b0_score,
            "squeeze_boost": b4_score,
            "weekly_boost": b6_score,
            **rp,
        })

    picks.sort(key=lambda x: -x["score"])

    # LLM conviction court — final qualitative filter
    if use_llm and _USE_LLM and picks:
        pre_court = len(picks)
        picks = llm_conviction_court(picks, ohlcv, regime)
        if len(picks) < pre_court:
            funnel["llm_court_rejected"] = pre_court - len(picks)
        # Re-sort by LLM conviction (if available) then score
        picks.sort(key=lambda x: (-x.get("llm_conviction", x["score"]), -x["score"]))

    picks = picks[:P.MAX_PICKS]
    return picks, dict(funnel)


# ═══════════════════════════════════════════════════════════════════════════════
# BACKTESTER
# ═══════════════════════════════════════════════════════════════════════════════

def find_bench_ticker(ohlcv):
    """Find Nifty 500 benchmark DataFrame from cache or Angel One."""
    for c in ["^CRSLDX.NS", "^CRSLDX", "NIFTY500.NS"]:
        if c in ohlcv: return ohlcv[c]
    try:
        sys.path.insert(0, SCRIPT_DIR)
        from angel_client import angel_download
        df = angel_download("^CRSLDX", TODAY - datetime.timedelta(days=500),
                            TODAY + datetime.timedelta(days=1))
        if not df.empty: return df
    except Exception: pass
    return None


def run_backtest(ohlcv, start_date=None, end_date=None, interval_days=7,
                 verbose=False, use_llm=False):
    """Backtest the scanner across historical dates at weekly intervals."""
    all_dates = sorted({d for df in ohlcv.values() for d in df.index.date})
    if not all_dates: return {"error": "no_dates"}
    if start_date is None:
        start_date = all_dates[min(P.MIN_HISTORY_DAYS + 30, len(all_dates)-1)]
    if end_date is None:
        end_date = all_dates[max(0, len(all_dates) - P.OUTCOME_DAYS - 2)]

    bench_df = find_bench_ticker(ohlcv)
    bench_close = bench_df["Close"] if bench_df is not None else pd.Series(dtype=float)

    test_dates = []
    cur = start_date
    while cur <= end_date:
        nearest = next((d for d in all_dates if d >= cur), None)
        if nearest and nearest <= end_date: test_dates.append(nearest)
        cur += datetime.timedelta(days=interval_days)

    print(f"\n  Backtest: {len(test_dates)} test dates from {start_date} to {end_date}")

    all_picks = []; weekly_results = []
    for i, td in enumerate(test_dates):
        sliced = slice_data(ohlcv, td)
        if not sliced: continue

        bc = bench_close[bench_close.index.date <= td] if not bench_close.empty else pd.Series(dtype=float)
        ratings = compute_rs_ratings(sliced, bc) if len(bc) > 60 else {}
        if not ratings:
            perfs = {tk: float(d["Close"].iloc[-1]/d["Close"].iloc[-min(60,len(d))]-1)
                     for tk, d in sliced.items() if len(d) >= 60}
            if perfs:
                vs = sorted(perfs.values()); n = len(vs)
                ratings = {tk: round(np.searchsorted(vs, p, side='right')/n*100, 1)
                           for tk, p in perfs.items()}

        bench_slice = bench_df[bench_df.index.date <= td] if bench_df is not None else pd.DataFrame()
        picks, funnel = run_scan(sliced, bench_slice, ratings, use_llm=use_llm)

        n_success = 0
        for pick in picks:
            if pick["ticker"] not in ohlcv: continue
            outcome = get_outcome(ohlcv[pick["ticker"]], td, pick["resistance"])
            all_picks.append({"test_date": td, **pick, **outcome})
            if outcome["success"]: n_success += 1

        sr = (n_success/len(picks)*100) if picks else None
        weekly_results.append({"date": td, "n_picks": len(picks),
                               "n_success": n_success, "success_rate": sr})
        if verbose or (i+1) % 10 == 0:
            s = f"{sr:.0f}%" if sr is not None else "N/A"
            print(f"    [{i+1}/{len(test_dates)}] {td}: {len(picks)} picks, {n_success} ok, SR={s}")

    total = len(all_picks)
    success = sum(1 for p in all_picks if p.get("success"))
    overall_sr = success/total*100 if total else 0
    weeks_wp = [w for w in weekly_results if w["n_picks"] > 0]
    wsrs = [w["success_rate"] for w in weeks_wp if w["success_rate"] is not None]
    avg_wsr = np.mean(wsrs) if wsrs else 0
    avg_gain = np.mean([p["max_gain_pct"] for p in all_picks]) if all_picks else 0
    avg_dd = np.mean([p["max_drawdown_pct"] for p in all_picks]) if all_picks else 0

    return {"total_picks": total, "total_success": success,
            "overall_success_rate": round(overall_sr, 1),
            "avg_weekly_success_rate": round(avg_wsr, 1),
            "n_test_dates": len(test_dates), "n_weeks_with_picks": len(weeks_wp),
            "avg_picks_per_week": round(total/max(1, len(weeks_wp)), 1),
            "avg_max_gain_pct": round(avg_gain, 2),
            "avg_max_drawdown_pct": round(avg_dd, 2),
            "all_picks": all_picks, "weekly_results": weekly_results}


def print_backtest_results(r):
    """Print formatted backtest results to console."""
    print("\n" + "="*70)
    print("  BACKTEST RESULTS")
    print("="*70)
    print(f"  Test periods:          {r['n_test_dates']}")
    print(f"  Weeks with picks:      {r['n_weeks_with_picks']}")
    print(f"  Total picks:           {r['total_picks']}")
    print(f"  Total breakouts:       {r['total_success']}")
    print(f"  Overall success rate:  {r['overall_success_rate']:.1f}%")
    print(f"  Avg weekly SR:         {r['avg_weekly_success_rate']:.1f}%")
    print(f"  Avg picks/week:        {r['avg_picks_per_week']:.1f}")
    print(f"  Avg max gain:          {r['avg_max_gain_pct']:.2f}%")
    print(f"  Avg max drawdown:      {r['avg_max_drawdown_pct']:.2f}%")
    print("="*70)

    failed = [p for p in r.get("all_picks", []) if not p.get("success")]
    if failed:
        print(f"\n  Failed picks ({len(failed)}):")
        for p in failed[:20]:
            print(f"    {p['test_date']} {p['ticker']}: R={p['resistance']}, "
                  f"gain={p['max_gain_pct']:.1f}%, dd={p['max_drawdown_pct']:.1f}%")

    # Worst weeks
    bad = [w for w in r.get("weekly_results", [])
           if w["n_picks"] > 0 and w["success_rate"] is not None and w["success_rate"] < 70]
    if bad:
        print(f"\n  Weeks below 70%:")
        for w in sorted(bad, key=lambda x: x["success_rate"] or 100):
            print(f"    {w['date']}: {w['n_picks']} picks, {w['n_success']} ok ({w['success_rate']:.0f}%)")


# ═══════════════════════════════════════════════════════════════════════════════
# EXCEL OUTPUT
# ═══════════════════════════════════════════════════════════════════════════════

def write_excel(picks, funnel, out_path=None):
    """Write scan results and funnel stats to Excel."""
    if out_path is None: out_path = os.path.join(SCRIPT_DIR, "breakout_v5_watchlist.xlsx")
    with pd.ExcelWriter(out_path, engine="openpyxl") as w:
        if picks:
            df = pd.DataFrame(picks)
            cols = ["ticker", "score", "close", "resistance", "distance_pct",
                    "rs_rating", "touches", "base_days", "base_range",
                    "higher_lows", "n_vcp", "squeeze_type", "institutional",
                    "weekly_rsi", "market_boost", "squeeze_boost", "weekly_boost",
                    "entry", "stop", "target", "risk_pct", "reward_pct", "rr"]
            df[[c for c in cols if c in df.columns]].to_excel(
                w, sheet_name="Breakout Candidates", index=False)
        else:
            pd.DataFrame({"Note": ["No stocks recommended"]}).to_excel(
                w, sheet_name="Breakout Candidates", index=False)
        pd.DataFrame([{"Gate": k, "Count": v} for k, v in sorted(funnel.items())]).to_excel(
            w, sheet_name="Funnel", index=False)
    print(f"\n  📊 Excel: {out_path}")


def write_backtest_excel(results, out_path=None):
    """Write backtest results to Excel with summary and all picks."""
    if out_path is None: out_path = os.path.join(SCRIPT_DIR, "breakout_v5_backtest.xlsx")
    with pd.ExcelWriter(out_path, engine="openpyxl") as w:
        summary = {"Metric": ["Total Picks", "Breakouts", "Success Rate", "Avg Weekly SR",
                               "Avg Picks/Week", "Avg Max Gain", "Avg Max DD"],
                   "Value": [results['total_picks'], results['total_success'],
                             f"{results['overall_success_rate']:.1f}%",
                             f"{results['avg_weekly_success_rate']:.1f}%",
                             results['avg_picks_per_week'],
                             f"{results['avg_max_gain_pct']:.2f}%",
                             f"{results['avg_max_drawdown_pct']:.2f}%"]}
        pd.DataFrame(summary).to_excel(w, sheet_name="Summary", index=False)
        ap = results.get("all_picks", [])
        if ap:
            df = pd.DataFrame(ap)
            cols = ["test_date", "ticker", "score", "close", "resistance",
                    "distance_pct", "rs_rating", "success", "max_gain_pct",
                    "max_drawdown_pct", "days_to_breakout"]
            df[[c for c in cols if c in df.columns]].to_excel(w, sheet_name="All Picks", index=False)
    print(f"\n  📊 Backtest Excel: {out_path}")


# ═══════════════════════════════════════════════════════════════════════════════
# LIVE SCANNER
# ═══════════════════════════════════════════════════════════════════════════════

def run_live_scan(verbose=False, use_llm=True):
    """Run a live scan on cached data and output to console + Excel."""
    global _USE_LLM
    _USE_LLM = use_llm

    print("\n  Breakout V5.1 — Adaptive Conviction Engine")
    print("  " + "="*50)
    ohlcv = load_all_cached_ohlcv()
    if not ohlcv:
        print("  ERROR: No cached data."); return []

    bench_df = find_bench_ticker(ohlcv)
    bench_close = bench_df["Close"] if bench_df is not None else pd.Series(dtype=float)

    print("  Computing RS ratings...")
    ratings = compute_rs_ratings(ohlcv, bench_close)

    print("  Running scan (3 hard gates + score boosters + LLM intelligence)...")
    picks, funnel = run_scan(ohlcv, bench_df if bench_df is not None else pd.DataFrame(),
                             ratings, verbose=verbose, use_llm=use_llm)

    print(f"\n  FUNNEL:")
    for k, v in sorted(funnel.items()):
        print(f"    {k}: {v}")

    if not picks:
        print("\n  ⚠️  No stocks met minimum conviction score.")
        write_excel([], funnel); return []

    print(f"\n  {'='*70}")
    print(f"  BREAKOUT CANDIDATES ({len(picks)} stocks, min score={P.MIN_SCORE})")
    print(f"  {'='*70}")
    for i, p in enumerate(picks[:20], 1):
        risk_flag = " ⚠️ WEAK MKT" if p.get("market_boost", 0) < 5 else ""
        print(f"\n  #{i} {p['ticker']} — Score: {p['score']}/100{risk_flag}")
        print(f"     Close: ₹{p['close']}  |  R: ₹{p['resistance']}  |  Dist: {p['distance_pct']:.1f}%")
        print(f"     RS: {p['rs_rating']:.0f}  |  Touches: {p['touches']}  |  Base: {p['base_days']}d")
        print(f"     Squeeze: {p['squeeze_type'] or 'none'}  |  Inst: {p['institutional']}")
        print(f"     Entry: ₹{p['entry']}  Stop: ₹{p['stop']}  Target: ₹{p['target']}  R:R={p['rr']}")

    write_excel(picks, funnel)
    return picks


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    """CLI entry point: --backtest for historical test, default for live scan."""
    p = argparse.ArgumentParser(description="Breakout V5.1 — Adaptive Conviction Engine")
    p.add_argument("--backtest", action="store_true")
    p.add_argument("--verbose", "-v", action="store_true")
    p.add_argument("--no-llm", action="store_true",
                   help="Skip LLM intelligence layer (regime, conviction court)")
    args = p.parse_args()

    use_llm = not args.no_llm

    if args.backtest:
        print("\n  Loading cached OHLCV data...")
        ohlcv = load_all_cached_ohlcv()
        if not ohlcv: print("  ERROR: No data."); sys.exit(1)
        results = run_backtest(ohlcv, verbose=args.verbose, use_llm=use_llm)
        print_backtest_results(results)
        write_backtest_excel(results)
    else:
        run_live_scan(verbose=args.verbose, use_llm=use_llm)


if __name__ == "__main__":
    main()
